package generator

const (
	GenFileTemplate = `
{{$info := .}}

//go:build easyhide
package main

// Code generated by easyhide. DO NOT EDIT.

import (
	"log"

	easyhide "github.com/denis96z/go-easyhide/pkg/easyhide/generator"

	{{$info.Pkg.Name}} {{printf "%q" $info.Pkg.Path}}
)

var (
	{{range $idx, $tp := $info.Types}}
		v{{$idx}} = {{$info.Pkg.Name}}.{{$tp.Name}}{}
	{{end}}
)

const (
	GeneratedFilePath = {{printf "%q" $info.GeneratedFilePath}}
)

func main() {
	gData := easyhide.GenData{
		PkgName: {{printf "%q" $info.Pkg.Name}},

		Types: make([]easyhide.GenDataTypeInfo, 0),
	}
	{{range $idx, $tp := $info.Types}}
		{
			var gdtpInfo easyhide.GenDataTypeInfo
			gdtpInfo.TypeCode, gdtpInfo.FuncCode = easyhide.GenerateCodeForType(v{{$idx}}, "{{$tp.Name}}")

			gData.Types = append(gData.Types, gdtpInfo)
		}
	{{end}}
	if err := easyhide.WriteEasyHideFile(GeneratedFilePath, gData); err != nil {
		log.Fatal(err)
	}
}
`
)
