// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package sample

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson291b620aDecodeGithubComDenis96zGoEasyhideSample(in *jlexer.Lexer, out *tp1f93603db53bfad5c92390f735d0cbb8617b4ab8214ae91c5664a3d1e9b009c8) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "a1":
			out.A1 = string(in.String())
		case "a2":
			out.A2 = string(in.String())
		case "A3":
			out.A3 = string(in.String())
		case "A4":
			out.A4 = string(in.String())
		case "A5":
			out.A5 = string(in.String())
		case "A6":
			out.A6 = string(in.String())
		case "A7":
			out.A7 = string(in.String())
		case "A8":
			out.A8 = string(in.String())
		case "A9":
			out.A9 = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson291b620aEncodeGithubComDenis96zGoEasyhideSample(out *jwriter.Writer, in tp1f93603db53bfad5c92390f735d0cbb8617b4ab8214ae91c5664a3d1e9b009c8) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"a1\":"
		out.RawString(prefix[1:])
		out.String(string(in.A1))
	}
	{
		const prefix string = ",\"a2\":"
		out.RawString(prefix)
		out.String(string(in.A2))
	}
	{
		const prefix string = ",\"A3\":"
		out.RawString(prefix)
		out.String(string(in.A3))
	}
	{
		const prefix string = ",\"A4\":"
		out.RawString(prefix)
		out.String(string(in.A4))
	}
	{
		const prefix string = ",\"A5\":"
		out.RawString(prefix)
		out.String(string(in.A5))
	}
	{
		const prefix string = ",\"A6\":"
		out.RawString(prefix)
		out.String(string(in.A6))
	}
	{
		const prefix string = ",\"A7\":"
		out.RawString(prefix)
		out.String(string(in.A7))
	}
	{
		const prefix string = ",\"A8\":"
		out.RawString(prefix)
		out.String(string(in.A8))
	}
	{
		const prefix string = ",\"A9\":"
		out.RawString(prefix)
		out.String(string(in.A9))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v tp1f93603db53bfad5c92390f735d0cbb8617b4ab8214ae91c5664a3d1e9b009c8) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson291b620aEncodeGithubComDenis96zGoEasyhideSample(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v tp1f93603db53bfad5c92390f735d0cbb8617b4ab8214ae91c5664a3d1e9b009c8) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson291b620aEncodeGithubComDenis96zGoEasyhideSample(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *tp1f93603db53bfad5c92390f735d0cbb8617b4ab8214ae91c5664a3d1e9b009c8) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson291b620aDecodeGithubComDenis96zGoEasyhideSample(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *tp1f93603db53bfad5c92390f735d0cbb8617b4ab8214ae91c5664a3d1e9b009c8) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson291b620aDecodeGithubComDenis96zGoEasyhideSample(l, v)
}
